# 主色调蓝色： #0084ff
# hover：     #006bde
# onerror="javascript:this.src='{{ with $.Site.Params.cdnURL }}{{ . }}{{ end }}{{ $.Site.Params.defaultLogo }}'"

baseURL               = "https://spiderbox.cn/"
languageCode          = "zh-CN"
title                 = "SpiderBox - 虫盒 - 爬虫逆向资源导航站"
theme                 = "webstack"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "docs"	# 站点静态文件保存目录


[params]
    author        = "ITBOB"
    keywords      = "爬虫，逆向，JS逆向，APP逆向，数据采集，SpiderBox，虫盒，资源导航，爬虫资源，逆向资源，资源导航站"
    description   = "SpiderBox - 虫盒 - 爬虫逆向资源导航站，数据采集、网络爬虫、JS逆向、APP逆向、小程序逆向等相关资源聚合、收集。"
    cdnURL        = "https://static.wukongsec.com/spiderbox/"      # CDN 地址，置空则不使用 CDN
    cdnURLPubilc  = "https://static.wukongsec.com/public/"         # CDN 地址，置空则不使用 CDN
    repository    = "https://github.com/WuKongSecurity"    # 左侧导航栏的"GitHub"
    submit        = "https://wj.qq.com/s2/25576072/4e39/"  # 左侧导航栏的提交收录
    enablePreLoad = true					               # 网站完全打开前预加载动画
    textPreLoad   = "SpiderBox 加载中..."				    # 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false					               # 默认展开左侧边导航栏（已失效，默认不展开，会记住用户的行为，下次打开会保持）
    logosPath     = "images/logo"			               # 网站每个导航地址logo存放地址
    defaultLogo   = "images/logo/default.png"		       # logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = false					               # 默认站点为深色(夜间)模式
    yiyan         = true                         		   # 默认启用一言服务
    showArticle   = true					               # 默认显示最新文章

[params.seo]    
    baiduhmid     = "eb388f839300d98c08f2a2a5edc02ec1"     # 百度统计 hm.src 的 ID
    baiduSiteVer  = "codeva-cnyCL4azyb"				       # 百度HTML标签验证(baidu-site-verification)
    tj51laid      = "3FcHt9RWSQ8XvN5u"                     # 51.LA 网站统计
    tj51lack      = "3FcHt9RWSQ8XvN5u"

[params.seniverse]
    key = "a39cd5a0-4024-4cb2-85c6-0250317058db"

[params.images]
    favicon           = "images/favicon.ico"
    appleTouchIcon    = "images/favicon.png"
    searchImageL      = "images/friends2.jpg"		# 搜索部分浅色背景图
    searchImageD      = "images/bg-dna.jpg"		    # 搜索部分深色背景图
    logoExpandLight   = "images/logo.png"
    logoExpandDark    = "images/logo.png"
    logoCollapseLight = "images/favicon.png"
    logoCollapseDark  = "images/favicon.png"

[params.info]
    email = "admin@itbob.cn"
    emailHref = "mailto:admin@itbob.cn"

[markup.goldmark.renderer]
    unsafe = true

[minify]
    minifyOutput = true
