baseURL               = "https://spiderbox.cn/"
languageCode          = "zh-CN"
title                 = "SpiderBox - 虫盒 - 爬虫资源导航"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "docs"					# 站点静态文件保存目录


[params]
    author        = "BOB"
    description   = "SpiderBox | 虫盒 | 爬虫逆向资源导航站"
    upload        = ""  # 左侧导航栏的"网站提交"
    about         = ""	# 左侧导航栏的"关于导航"(./about)
    repository    = "https://github.com/TRHX/spiderbox"    # 左侧导航栏的"GitHub"
    enablePreLoad = true					               # 网站完全打开前预加载动画
    textPreLoad   = "SpiderBox 加载中..."				   # 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = true					# 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			# 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/logos/default.webp"		# logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = false					# 默认站点为深色(夜间)模式
    yiyan         = true                         		# 默认启用一言服务

[params.seo]    
    baiduhmid     = 'efccc04cb44fc49faddac5876180b369'		# 百度统计 hm.src 的 ID
    baiduSiteVer  = 'codeva-cCAOSG8MBO'				# 百度HTML标签验证(baidu-site-verification)
    tj51laid        = ''                        		# 51.LA 网站统计
    tj51lack        = ''

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/favicon.ico"
    searchImageL      = "assets/images/friends2.jpg"		# 搜索部分浅色背景图
    searchImageD      = "assets/images/bg-dna.jpg"		    # 搜索部分深色背景图
    logoExpandLight   = "assets/images/logo_light.png"
    logoExpandDark    = "assets/images/logo_dark.png"
    logoCollapseLight = "assets/images/favicon.png"
    logoCollapseDark  = "assets/images/favicon.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '本站内容源自互联网，如有内容侵犯权益，请联系站长删除相关内容，联系邮箱：mail@xazz.top <br/><br/><span id="RunTime" style="color:#FC4E27;letter-spacing:2px"></span><br/><br/>&copy; 2023 - {year} By [WebStack-Hugo](https://github.com/shenweiyan/WebStack-Hugo) | [ikirito-Github](https://github.com/i-kirito) | [备案号](https://nav.xazz.top)<br/>'

# 蓝色 0084ff
